response = {
	GREETING_MESSAGE: "GREETING",
	ASK_FLIGHT_INFORMATION_MESSAGE: "ASK_FLIGHT_INFORMATION",
	ASK_CONFIRM_FLIGHT_MESSAGE: "ASK_CONFIRM_FLIGHT",
	SET_INBOUND_FLIGHT_MESSAGE: "SET_INBOUND_FLIGHT",
	SET_OUTBOUND_FLIGHT_MESSAGE: "SET_OUTBOUND_FLIGHT",
	ONLINE_CHECKIN_MESSAGE: "https://www.singaporeair.com/en_UK/plan-and-book/check-in-online/",
	COMMEND_PHOTO_MESSAGE: "COMMEND_PHOTO",
	ASK_RECOMMENDATIONS_MESSAGE: "ASK_RECOMMENDATIONS",
	FOOD_RECOMMENDATION_MESSAGE: "FOOD_RECOMMENDATION",
	ENTERTAINMENT_RECOMMENDATION_MESSAGE: "ENTERTAINMENT_RECOMMENDATION",
	UPLOAD_PHOTO_MESSAGE: "UPLOAD_PHOTO"
}

module.exports = response;